export const demoInputText = `Institution: Savanna Pay
Type: Fintech (payment service provider)
Markets: Nigeria and Kenya
Customer tier: Tier 2 retail
Auto-approve: 80
Decline below: 25
Environment: Production
Webhooks: Not yet configured`

export const ngSummaryText = `PREMBLY WORKFLOW SUMMARY
========================
Generated by: Prembly Workflow Builder AI Agent
Config ID: cfg_ng_tier2_savannapay_v1
Template used: Template A (retail_individual_v1)
Market: NG (Nigeria)
Customer tier: tier_2

INSTITUTION
-----------
Name: Savanna Pay
Type: Fintech (payment service provider)
Regulatory framework: CBN KYC Regulations 2023

ONBOARDING JOURNEY
------------------
1. Personal data collection - User provides basic profile details
2. Identity verification - BVN verified against NIBSS
3. Document verification - OCR cross-check of government ID
4. Liveness check - Biometric match against BVN photo
5. AML screening - PEP, sanctions (including CBN Watchlist), and adverse media
6. Scoring - Risk score calculated
7. Decision - Auto-approve, manual review, step-up, or decline
8. Ongoing monitoring - Activation of transaction monitoring

RISK THRESHOLDS
---------------
Auto-approve above: 80
Manual review: 50 – 79
Step-up required: 30 – 49
Auto-decline below: 25

DEVIATIONS FROM TEMPLATE DEFAULT
---------------------------------
- auto_decline_below changed from 30 to 25 (Institution preference)
- manual_review_range minimum implicitly set to 50
- step_up_range set to 30-49

MARKET-SPECIFIC COMPLIANCE NOTES
---------------------------------
- CBN_WATCHLIST added to sanctions lists (Mandatory for NG)
- hard_block_on_sanctions_hit enforced (Mandatory)
- CBN tier cap enforcement enabled for transaction volume limits
- NFIU reporting enabled
`

export const ngConfigJson = `{
  "template": "retail_individual_v1",
  "config_id": "cfg_ng_tier2_savannapay_v1",
  "tenant_id": "tnt_savannapay_001",
  "environment": "production",
  "market": "NG",
  "customer_tier": "tier_2",
  "customer_segment": "retail_individual",
  "identity": {
    "primary_anchor": "bvn",
    "fallback_anchor": "nin",
    "liveness_check": true,
    "liveness_provider": "prembly_biometric",
    "document_verification": {
      "enabled": true,
      "ocr_cross_check": true,
      "accepted_types": [
        "national_id",
        "passport",
        "drivers_licence"
      ]
    }
  },
  "aml": {
    "pep_screening": true,
    "sanctions_lists": [
      "OFAC",
      "UN",
      "EU",
      "CBN_WATCHLIST"
    ],
    "adverse_media": true,
    "adverse_media_categories": [
      "fraud",
      "money_laundering",
      "terrorism"
    ],
    "ongoing_monitoring": true,
    "monitoring_frequency": "daily"
  },
  "scoring": {
    "auto_approve_threshold": 80,
    "manual_review_range": {
      "min": 50,
      "max": 79
    },
    "step_up_range": {
      "min": 30,
      "max": 49
    },
    "auto_decline_below": 25,
    "hard_block_on_sanctions_hit": true
  },
  "step_up": {
    "triggers": [
      "liveness_inconclusive",
      "score_in_step_up_range",
      "document_tamper_suspected"
    ],
    "required_documents": [
      "utility_bill",
      "bank_statement"
    ],
    "expiry_hours": 48,
    "on_expiry": "escalate_to_manual_review"
  },
  "transaction_monitoring": {
    "enabled": true,
    "velocity_rules": {
      "max_daily_txn_count": 20,
      "max_daily_volume_local_currency": 500000
    },
    "pattern_alerts": [
      "round_sum",
      "structuring",
      "peer_anomaly"
    ],
    "sar_auto_draft_threshold": 40
  },
  "compliance": {
    "regulator": "CBN",
    "kyc_framework": "CBN_KYC_2023",
    "nfiu_reporting": true,
    "cbn_tier_cap_enforcement": true,
    "cdd_level": "standard",
    "edd_trigger_score": 45,
    "audit_log_retention_days": 2555
  },
  "webhooks": {
    "onboarding_decision": "PLACEHOLDER_REQUIRED",
    "score_change": "PLACEHOLDER_REQUIRED",
    "alert_triggered": "PLACEHOLDER_REQUIRED",
    "signing_secret": "PLACEHOLDER_REQUIRED"
  },
  "sdk": {
    "language": "en",
    "session_timeout_minutes": 15,
    "retry_limit": 2
  }
}`

export const keSummaryText = `PREMBLY WORKFLOW SUMMARY
========================
Generated by: Prembly Workflow Builder AI Agent
Config ID: cfg_ke_tier2_savannapay_v1
Template used: Template A (retail_individual_v1)
Market: KE (Kenya)
Customer tier: tier_2

INSTITUTION
-----------
Name: Savanna Pay
Type: Fintech (payment service provider)
Regulatory framework: POCAMLA 2023

ONBOARDING JOURNEY
------------------
1. Personal data collection - User provides basic profile details
2. Identity verification - Kenyan National ID verified against IPRS
3. Tax verification - KRA PIN validation
4. Document verification - OCR cross-check of ID
5. Liveness check - Biometric match
6. AML screening - PEP, sanctions (CBK & FRC), adverse media (including tax evasion)
7. Scoring - Risk score calculated
8. Decision - Routing
9. Ongoing monitoring - Activation

RISK THRESHOLDS
---------------
Auto-approve above: 80
Manual review: 50 – 79
Step-up required: 30 – 49
Auto-decline below: 25

MARKET-SPECIFIC COMPLIANCE NOTES
---------------------------------
- BVN replaced with National ID and IPRS check
- KRA PIN verification added
- CBK_WATCHLIST and FRC_WATCHLIST added to sanctions
- 'tax_evasion' added to adverse media categories (FRC requirement)
- FRC reporting enabled
`

export const keConfigJson = `{
  "template": "retail_individual_v1",
  "config_id": "cfg_ke_tier2_savannapay_v1",
  "tenant_id": "tnt_savannapay_001",
  "environment": "production",
  "market": "KE",
  "customer_tier": "tier_2",
  "customer_segment": "retail_individual",
  "identity": {
    "primary_anchor": "national_id",
    "fallback_anchor": "passport",
    "kra_pin_verification": true,
    "iprs_check": true,
    "liveness_check": true,
    "liveness_provider": "prembly_biometric",
    "document_verification": {
      "enabled": true,
      "ocr_cross_check": true,
      "accepted_types": [
        "national_id",
        "passport"
      ]
    }
  },
  "aml": {
    "pep_screening": true,
    "sanctions_lists": [
      "OFAC",
      "UN",
      "EU",
      "CBK_WATCHLIST",
      "FRC_WATCHLIST"
    ],
    "adverse_media": true,
    "adverse_media_categories": [
      "fraud",
      "money_laundering",
      "terrorism",
      "tax_evasion"
    ],
    "ongoing_monitoring": true,
    "monitoring_frequency": "daily"
  },
  "scoring": {
    "auto_approve_threshold": 80,
    "manual_review_range": {
      "min": 50,
      "max": 79
    },
    "step_up_range": {
      "min": 30,
      "max": 49
    },
    "auto_decline_below": 25,
    "hard_block_on_sanctions_hit": true
  },
  "step_up": {
    "triggers": [
      "liveness_inconclusive",
      "score_in_step_up_range",
      "document_tamper_suspected"
    ],
    "required_documents": [
      "utility_bill",
      "bank_statement",
      "kra_pin_certificate"
    ],
    "expiry_hours": 48,
    "on_expiry": "escalate_to_manual_review"
  },
  "transaction_monitoring": {
    "enabled": true,
    "velocity_rules": {
      "max_daily_txn_count": 20,
      "max_daily_volume_local_currency": 1000000
    },
    "pattern_alerts": [
      "round_sum",
      "structuring",
      "peer_anomaly"
    ],
    "sar_auto_draft_threshold": 40
  },
  "compliance": {
    "regulator": "CBK",
    "kyc_framework": "POCAMLA_2023",
    "frc_reporting": true,
    "cdd_level": "standard",
    "edd_trigger_score": 45,
    "audit_log_retention_days": 1825
  },
  "webhooks": {
    "onboarding_decision": "PLACEHOLDER_REQUIRED",
    "score_change": "PLACEHOLDER_REQUIRED",
    "alert_triggered": "PLACEHOLDER_REQUIRED",
    "signing_secret": "PLACEHOLDER_REQUIRED"
  },
  "sdk": {
    "language": "en",
    "session_timeout_minutes": 15,
    "retry_limit": 2
  }
}`

export const openItemsText = `OPEN ITEMS (both markets)
1. Webhook URLs not provided. Both configs have PLACEHOLDER_REQUIRED 
   in webhook fields. Do not deploy until real URLs are confirmed.
2. Step-up floor and manual review floor were not specified. 
   Defaults of 30 and 50 have been applied. Please confirm these 
   match your risk appetite.
3. Kenya config includes KRA PIN verification and IPRS check. 
   Please confirm your backend is ready to receive these additional 
   identity fields in the response payload.
`
